<?php

namespace FCS\CP\CpSplitViewBundle\Repository;

/**
 * CpLoadingPoSkuDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CpLoadingPoSkuDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
