<?php

namespace FCS\CP\CpSplitViewBundle\Repository;

/**
 * CpLoadingShowDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CpLoadingShowDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
