<?php

namespace FCS\CP\EditCpBundle\Repository;

/**
 * CpLoadingPoSkuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CpLoadingPoSkuRepository extends \Doctrine\ORM\EntityRepository
{
}
