<?php

namespace FCS\CP\EditCpBundle\Repository;

/**
 * CpLoadingShowAvailableSupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CpLoadingShowAvailableSupplierRepository extends \Doctrine\ORM\EntityRepository
{
}
